### PR TITLE
make resource identifier serializable

### PR DESCRIPTION
**Pull request by bavardage**

### CODE REVIEW

**Review by markelliot — APPROVED** [review]

**Comment by bavardage** [comment]
hmm, did this fall off circle somehow (didn't see a triggered circle build)

**Comment by gatesn** [comment]
Fixes #46 

@bavardage I don't think the repo is setup to run circle builds for forks

Also, ping on this!

**Comment by markelliot** [comment]
Not convinced we should do this. RIs have exactly one valid serialized form.

**Comment by bavardage** [comment]
this is for spark, where you don't control the serialization

currently you have to make sure that for any class serialized by spark/captured by a spark closure, you instead store a `String`/make sure only a `String` is captured by the closure and then you have to turn it back into an rid whenever you want to actually use it.

@markelliot do you think the dance with strings beats adding `Serializable`?

**Comment by markelliot** [comment]
The implication is roughly that there's two serialized forms of the thing, which seems risky. How crazy would it be to add the read/write methods to ensure the formats are the same?

**Comment by gatesn** [comment]
So is the solution to implement the readObject and writeObject using ::toString and ::of?

That way we're serializabke with a single format.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by markelliot** [comment]
Yeah, I think that'll do it.

On Jul 7, 2017, at 01:13, Nicholas Gates <notifications@github.com<mailto:notifications@github.com>> wrote:

So is the solution to implement the readObject and writeObject using ::toString and ::of?

That way we're serializabke with a single format.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bavardage** [comment]
Yes except readObject isn't static/may have some fun with the finals: I didn't try yet...

Sent from my iPhone

On Jul 6, 2017, at 7:13 PM, Nicholas Gates <notifications@github.com<mailto:notifications@github.com>> wrote:

So is the solution to implement the readObject and writeObject using ::toString and ::of?

That way we're serializabke with a single format.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by markelliot** [comment]
You can readResolve for that, I believe.

On Jul 7, 2017, at 01:15, Ben Duffield <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes except readObject isn't static/may have some fun with the finals: I didn't try yet...

Sent from my iPhone

On Jul 6, 2017, at 7:13 PM, Nicholas Gates <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

So is the solution to implement the readObject and writeObject using ::toString and ::of?

That way we're serializabke with a single format.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by uschi2000** [comment]
this is pretty old, closing

**Pull request closed without merging**
