### PR TITLE
Make ResourceIdentifier non-final

### PR DESCRIPTION
**Pull request by j-baker**
A number of internal projects use ResourceIdentifier, which is a final class. This makes it much harder to use tools like Antipatterns, because you have to FBSuppressWarnings every single usage of ResourceIdentifier.

It'd be great if we could remove this restriction, as the advantages of it being final don't obviously outweigh this big negative.

### CODE REVIEW

**Comment by iamdanfox** [comment]
Maybe worth bumping the baseline version from 0.2.5 to 0.8.0?

**Comment by markelliot** [comment]
Sorry, the intent for this class is to be sealed (like `String`).

**Comment by j-baker** [comment]
ResourceIdentifier has only a private constructor, and so there's no benefit from the class being final (you can't subclass anyway).

Given that finality breaks useful tools like smart nulls and antipatterns, it seems that the class being final is a wholly negative attribute.

To the best of my knowledge, the reason why String is final is for security and performance reasons, which doesn't seem to apply here (String is used in the classloading process so subclassing it is problematic, and it's much easier to write e.g. optimised assembly for comparing strings if you know there's no subtyping taking place).

**Comment by diogoholanda** [comment]
I just got the same problem when updating baseline in a repository.
I think this is causing more pain than benefits. Could we reconsider this?

**Pull request closed without merging**
