### PR TITLE
Remove unused CharBuffer

### PR DESCRIPTION
**Pull request by schlosna**
Fixup from https://github.com/palantir/resource-identifier/pull/49/files#r182920353

@aborochoff @markelliot for review & merge since I can't assign on this project

### CODE REVIEW

**Review by markelliot — APPROVED** [review]

**Comment by schlosna** [comment]
@markelliot I don't have merge privileges on this repo, would you mind merging at will?

**Comment by schlosna** [comment]
looks like this is also a dupe of #54 . would be good to merge one of these and cut a release to avoid the memory bloat

**Comment by schlosna** [comment]
this is also dupe of #50

**Review by markelliot — APPROVED** [review]

**Comment by markelliot** [comment]
Looks like maybe this isn’t triggering circle builds now?

**Comment by ellisjoe** [comment]
merged https://github.com/palantir/resource-identifier/pull/50

**Pull request closed without merging**
