### PR TITLE
Modernize repo

### PR DESCRIPTION
**Pull request by ferozco**

### CODE REVIEW

**Comment by carterkozak** [comment]
lgtm, but I don't have perms. something is off with the cache in the jdk11 build.

**Comment by ferozco** [comment]
It actually looks like the gradle is 4 years old and so it doesn't support Java 11

**Comment by ferozco** [comment]
Policy bot will only go into effect once the PR is merged, but otherwise this should be all set

**Review by carterkozak — APPROVED** [review]
Thanks!

**Pull request merged**
